version: '0.0.1-{build}'

clone_folder: c:\projects\myproject

platform:
  - x86
  - Any CPU

build_script:
  - cmake .

after_build:
  - 7z a myapp.zip %APPVEYOR_BUILD_FOLDER%\

artifacts:
  - path: myapp.zip
    name: MyApp
